name: Laravel

on:
  push:
    branches: [ master ]

jobs:
  laravel-deployment:

    runs-on: self-hosted

    steps:
      - name: Checkout and fetch
        working-directory: /var/www/html/github-actions-training
        run: |
          git checkout -- .
          git pull origin master
